var annotated_dup =
[
    [ "common", "namespacecommon.html", [
      [ "error_info", "structcommon_1_1error__info.html", "structcommon_1_1error__info" ],
      [ "Result", "classcommon_1_1Result.html", "classcommon_1_1Result" ]
    ] ],
    [ "database", "namespacedatabase.html", [
      [ "async", "namespacedatabase_1_1async.html", [
        [ "async_database", "classdatabase_1_1async_1_1async__database.html", "classdatabase_1_1async_1_1async__database" ],
        [ "async_executor", "classdatabase_1_1async_1_1async__executor.html", "classdatabase_1_1async_1_1async__executor" ],
        [ "async_result", "classdatabase_1_1async_1_1async__result.html", "classdatabase_1_1async_1_1async__result" ],
        [ "fallback_context", "classdatabase_1_1async_1_1fallback__context.html", "classdatabase_1_1async_1_1fallback__context" ],
        [ "result_type", "classdatabase_1_1async_1_1result__type.html", "classdatabase_1_1async_1_1result__type" ],
        [ "result_void_type", "classdatabase_1_1async_1_1result__void__type.html", "classdatabase_1_1async_1_1result__void__type" ],
        [ "saga_builder", "classdatabase_1_1async_1_1saga__builder.html", "classdatabase_1_1async_1_1saga__builder" ],
        [ "stream_processor", "classdatabase_1_1async_1_1stream__processor.html", "classdatabase_1_1async_1_1stream__processor" ],
        [ "transaction_coordinator", "classdatabase_1_1async_1_1transaction__coordinator.html", "classdatabase_1_1async_1_1transaction__coordinator" ]
      ] ],
      [ "backends", "namespacedatabase_1_1backends.html", [
        [ "mongodb_backend", "classdatabase_1_1backends_1_1mongodb__backend.html", "classdatabase_1_1backends_1_1mongodb__backend" ],
        [ "postgresql_backend", "classdatabase_1_1backends_1_1postgresql__backend.html", "classdatabase_1_1backends_1_1postgresql__backend" ],
        [ "redis_backend", "classdatabase_1_1backends_1_1redis__backend.html", "classdatabase_1_1backends_1_1redis__backend" ],
        [ "sqlite_backend", "classdatabase_1_1backends_1_1sqlite__backend.html", "classdatabase_1_1backends_1_1sqlite__backend" ]
      ] ],
      [ "core", "namespacedatabase_1_1core.html", [
        [ "backend_base", "classdatabase_1_1core_1_1backend__base.html", "classdatabase_1_1core_1_1backend__base" ],
        [ "backend_registrar", "classdatabase_1_1core_1_1backend__registrar.html", "classdatabase_1_1core_1_1backend__registrar" ],
        [ "backend_registry", "classdatabase_1_1core_1_1backend__registry.html", "classdatabase_1_1core_1_1backend__registry" ],
        [ "connection_config", "structdatabase_1_1core_1_1connection__config.html", "structdatabase_1_1core_1_1connection__config" ],
        [ "database_backend", "classdatabase_1_1core_1_1database__backend.html", "classdatabase_1_1core_1_1database__backend" ]
      ] ],
      [ "detail", "namespacedatabase_1_1detail.html", [
        [ "sql_dialect", "classdatabase_1_1detail_1_1sql__dialect.html", "classdatabase_1_1detail_1_1sql__dialect" ]
      ] ],
      [ "integrated", "namespacedatabase_1_1integrated.html", [
        [ "adapters", "namespacedatabase_1_1integrated_1_1adapters.html", [
          [ "backends", "namespacedatabase_1_1integrated_1_1adapters_1_1backends.html", [
            [ "common_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1common__logger__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1common__logger__backend" ],
            [ "fallback_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__logger__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__logger__backend" ],
            [ "fallback_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__monitoring__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__monitoring__backend" ],
            [ "fallback_thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__thread__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__thread__backend" ],
            [ "health_check_result", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1health__check__result.html", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1health__check__result" ],
            [ "logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1logger__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1logger__backend" ],
            [ "metrics_snapshot", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1metrics__snapshot.html", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1metrics__snapshot" ],
            [ "monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1monitoring__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1monitoring__backend" ],
            [ "null_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__logger__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__logger__backend" ],
            [ "null_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__monitoring__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__monitoring__backend" ],
            [ "null_thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__thread__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__thread__backend" ],
            [ "system_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1system__monitoring__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1system__monitoring__backend" ],
            [ "thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1thread__backend.html", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1thread__backend" ]
          ] ],
          [ "database_metrics", "structdatabase_1_1integrated_1_1adapters_1_1database__metrics.html", "structdatabase_1_1integrated_1_1adapters_1_1database__metrics" ],
          [ "logger_adapter", "classdatabase_1_1integrated_1_1adapters_1_1logger__adapter.html", "classdatabase_1_1integrated_1_1adapters_1_1logger__adapter" ],
          [ "monitoring_adapter", "classdatabase_1_1integrated_1_1adapters_1_1monitoring__adapter.html", "classdatabase_1_1integrated_1_1adapters_1_1monitoring__adapter" ],
          [ "thread_adapter", "classdatabase_1_1integrated_1_1adapters_1_1thread__adapter.html", "classdatabase_1_1integrated_1_1adapters_1_1thread__adapter" ]
        ] ],
        [ "connection_string_builder", "classdatabase_1_1integrated_1_1connection__string__builder.html", "classdatabase_1_1integrated_1_1connection__string__builder" ],
        [ "database_config", "structdatabase_1_1integrated_1_1database__config.html", "structdatabase_1_1integrated_1_1database__config" ],
        [ "database_coordinator", "classdatabase_1_1integrated_1_1database__coordinator.html", "classdatabase_1_1integrated_1_1database__coordinator" ],
        [ "database_metrics", "structdatabase_1_1integrated_1_1database__metrics.html", "structdatabase_1_1integrated_1_1database__metrics" ],
        [ "db_logger_config", "structdatabase_1_1integrated_1_1db__logger__config.html", "structdatabase_1_1integrated_1_1db__logger__config" ],
        [ "db_monitoring_config", "structdatabase_1_1integrated_1_1db__monitoring__config.html", "structdatabase_1_1integrated_1_1db__monitoring__config" ],
        [ "db_thread_config", "structdatabase_1_1integrated_1_1db__thread__config.html", "structdatabase_1_1integrated_1_1db__thread__config" ],
        [ "health_check", "structdatabase_1_1integrated_1_1health__check.html", "structdatabase_1_1integrated_1_1health__check" ],
        [ "pool_config", "structdatabase_1_1integrated_1_1pool__config.html", "structdatabase_1_1integrated_1_1pool__config" ],
        [ "query_param", "structdatabase_1_1integrated_1_1query__param.html", "structdatabase_1_1integrated_1_1query__param" ],
        [ "query_result", "structdatabase_1_1integrated_1_1query__result.html", "structdatabase_1_1integrated_1_1query__result" ],
        [ "transaction", "classdatabase_1_1integrated_1_1transaction.html", "classdatabase_1_1integrated_1_1transaction" ],
        [ "transaction_impl", "classdatabase_1_1integrated_1_1transaction__impl.html", "classdatabase_1_1integrated_1_1transaction__impl" ],
        [ "unified_database_system", "classdatabase_1_1integrated_1_1unified__database__system.html", "classdatabase_1_1integrated_1_1unified__database__system" ],
        [ "unified_db_config", "structdatabase_1_1integrated_1_1unified__db__config.html", "structdatabase_1_1integrated_1_1unified__db__config" ]
      ] ],
      [ "monitoring", "namespacedatabase_1_1monitoring.html", [
        [ "connection_metrics", "structdatabase_1_1monitoring_1_1connection__metrics.html", "structdatabase_1_1monitoring_1_1connection__metrics" ],
        [ "dashboard_server", "classdatabase_1_1monitoring_1_1dashboard__server.html", "classdatabase_1_1monitoring_1_1dashboard__server" ],
        [ "metrics_exporter", "classdatabase_1_1monitoring_1_1metrics__exporter.html", "classdatabase_1_1monitoring_1_1metrics__exporter" ],
        [ "performance_alert", "classdatabase_1_1monitoring_1_1performance__alert.html", "classdatabase_1_1monitoring_1_1performance__alert" ],
        [ "performance_monitor", "classdatabase_1_1monitoring_1_1performance__monitor.html", "classdatabase_1_1monitoring_1_1performance__monitor" ],
        [ "performance_summary", "structdatabase_1_1monitoring_1_1performance__summary.html", "structdatabase_1_1monitoring_1_1performance__summary" ],
        [ "pool_metrics", "structdatabase_1_1monitoring_1_1pool__metrics.html", "structdatabase_1_1monitoring_1_1pool__metrics" ],
        [ "prometheus_exporter", "classdatabase_1_1monitoring_1_1prometheus__exporter.html", "classdatabase_1_1monitoring_1_1prometheus__exporter" ],
        [ "query_metrics", "structdatabase_1_1monitoring_1_1query__metrics.html", "structdatabase_1_1monitoring_1_1query__metrics" ],
        [ "query_timer", "classdatabase_1_1monitoring_1_1query__timer.html", "classdatabase_1_1monitoring_1_1query__timer" ]
      ] ],
      [ "orm", "namespacedatabase_1_1orm.html", [
        [ "entity_base", "classdatabase_1_1orm_1_1entity__base.html", "classdatabase_1_1orm_1_1entity__base" ],
        [ "entity_manager", "classdatabase_1_1orm_1_1entity__manager.html", "classdatabase_1_1orm_1_1entity__manager" ],
        [ "entity_metadata", "classdatabase_1_1orm_1_1entity__metadata.html", "classdatabase_1_1orm_1_1entity__metadata" ],
        [ "field_accessor", "classdatabase_1_1orm_1_1field__accessor.html", "classdatabase_1_1orm_1_1field__accessor" ],
        [ "field_metadata", "classdatabase_1_1orm_1_1field__metadata.html", "classdatabase_1_1orm_1_1field__metadata" ],
        [ "is_entity", "structdatabase_1_1orm_1_1is__entity.html", null ],
        [ "is_entity< T, std::void_t< typename T::primary_key_type, decltype(std::declval< T >().table_name()), decltype(std::declval< T >().get_metadata()) > >", "structdatabase_1_1orm_1_1is__entity_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1primary__key__9fe9349fbe2e5ada710d0512a44a53a9.html", null ],
        [ "query_builder", "classdatabase_1_1orm_1_1query__builder.html", "classdatabase_1_1orm_1_1query__builder" ]
      ] ],
      [ "protocol", "namespacedatabase_1_1protocol.html", [
        [ "connect_request", "structdatabase_1_1protocol_1_1connect__request.html", "structdatabase_1_1protocol_1_1connect__request" ],
        [ "connect_response", "structdatabase_1_1protocol_1_1connect__response.html", "structdatabase_1_1protocol_1_1connect__response" ],
        [ "error_response", "structdatabase_1_1protocol_1_1error__response.html", "structdatabase_1_1protocol_1_1error__response" ],
        [ "message_header", "structdatabase_1_1protocol_1_1message__header.html", "structdatabase_1_1protocol_1_1message__header" ],
        [ "protocol_serializer", "classdatabase_1_1protocol_1_1protocol__serializer.html", "classdatabase_1_1protocol_1_1protocol__serializer" ],
        [ "query_request", "structdatabase_1_1protocol_1_1query__request.html", "structdatabase_1_1protocol_1_1query__request" ],
        [ "query_response", "structdatabase_1_1protocol_1_1query__response.html", "structdatabase_1_1protocol_1_1query__response" ],
        [ "transaction_request", "structdatabase_1_1protocol_1_1transaction__request.html", "structdatabase_1_1protocol_1_1transaction__request" ],
        [ "transaction_response", "structdatabase_1_1protocol_1_1transaction__response.html", "structdatabase_1_1protocol_1_1transaction__response" ]
      ] ],
      [ "query", "namespacedatabase_1_1query.html", [
        [ "tests", "namespacedatabase_1_1query_1_1tests.html", [
          [ "CrossDialectTest", "classdatabase_1_1query_1_1tests_1_1CrossDialectTest.html", "classdatabase_1_1query_1_1tests_1_1CrossDialectTest" ],
          [ "PostgreSQLDialectTest", "classdatabase_1_1query_1_1tests_1_1PostgreSQLDialectTest.html", "classdatabase_1_1query_1_1tests_1_1PostgreSQLDialectTest" ],
          [ "SQLiteDialectTest", "classdatabase_1_1query_1_1tests_1_1SQLiteDialectTest.html", "classdatabase_1_1query_1_1tests_1_1SQLiteDialectTest" ]
        ] ],
        [ "condition", "structdatabase_1_1query_1_1condition.html", "structdatabase_1_1query_1_1condition" ],
        [ "condition_builder", "classdatabase_1_1query_1_1condition__builder.html", "classdatabase_1_1query_1_1condition__builder" ],
        [ "join_builder", "classdatabase_1_1query_1_1join__builder.html", "classdatabase_1_1query_1_1join__builder" ],
        [ "join_spec", "structdatabase_1_1query_1_1join__spec.html", "structdatabase_1_1query_1_1join__spec" ],
        [ "postgresql_dialect", "classdatabase_1_1query_1_1postgresql__dialect.html", "classdatabase_1_1query_1_1postgresql__dialect" ],
        [ "sql_dialect", "classdatabase_1_1query_1_1sql__dialect.html", "classdatabase_1_1query_1_1sql__dialect" ],
        [ "sqlite_dialect", "classdatabase_1_1query_1_1sqlite__dialect.html", "classdatabase_1_1query_1_1sqlite__dialect" ],
        [ "value_formatter", "classdatabase_1_1query_1_1value__formatter.html", "classdatabase_1_1query_1_1value__formatter" ]
      ] ],
      [ "security", "namespacedatabase_1_1security.html", [
        [ "access_control", "classdatabase_1_1security_1_1access__control.html", "classdatabase_1_1security_1_1access__control" ],
        [ "audit_log_entry", "structdatabase_1_1security_1_1audit__log__entry.html", "structdatabase_1_1security_1_1audit__log__entry" ],
        [ "audit_logger", "classdatabase_1_1security_1_1audit__logger.html", "classdatabase_1_1security_1_1audit__logger" ],
        [ "connection_security", "classdatabase_1_1security_1_1connection__security.html", "classdatabase_1_1security_1_1connection__security" ],
        [ "credential_manager", "classdatabase_1_1security_1_1credential__manager.html", "classdatabase_1_1security_1_1credential__manager" ],
        [ "encryption_manager", "classdatabase_1_1security_1_1encryption__manager.html", "classdatabase_1_1security_1_1encryption__manager" ],
        [ "query_security", "classdatabase_1_1security_1_1query__security.html", "classdatabase_1_1security_1_1query__security" ],
        [ "security_credentials", "structdatabase_1_1security_1_1security__credentials.html", "structdatabase_1_1security_1_1security__credentials" ],
        [ "security_monitor", "classdatabase_1_1security_1_1security__monitor.html", "classdatabase_1_1security_1_1security__monitor" ]
      ] ],
      [ "testing", "namespacedatabase_1_1testing.html", [
        [ "backend_exception", "classdatabase_1_1testing_1_1backend__exception.html", "classdatabase_1_1testing_1_1backend__exception" ],
        [ "backend_expectation", "classdatabase_1_1testing_1_1backend__expectation.html", "classdatabase_1_1testing_1_1backend__expectation" ],
        [ "backend_expectation_builder", "classdatabase_1_1testing_1_1backend__expectation__builder.html", "classdatabase_1_1testing_1_1backend__expectation__builder" ],
        [ "database_exception", "classdatabase_1_1testing_1_1database__exception.html", "classdatabase_1_1testing_1_1database__exception" ],
        [ "expectation", "classdatabase_1_1testing_1_1expectation.html", "classdatabase_1_1testing_1_1expectation" ],
        [ "expectation_builder", "classdatabase_1_1testing_1_1expectation__builder.html", "classdatabase_1_1testing_1_1expectation__builder" ],
        [ "mock_backend", "classdatabase_1_1testing_1_1mock__backend.html", "classdatabase_1_1testing_1_1mock__backend" ],
        [ "mock_backend_builder", "classdatabase_1_1testing_1_1mock__backend__builder.html", "classdatabase_1_1testing_1_1mock__backend__builder" ],
        [ "mock_connection_pool", "classdatabase_1_1testing_1_1mock__connection__pool.html", "classdatabase_1_1testing_1_1mock__connection__pool" ],
        [ "mock_database", "classdatabase_1_1testing_1_1mock__database.html", "classdatabase_1_1testing_1_1mock__database" ],
        [ "mock_database_builder", "classdatabase_1_1testing_1_1mock__database__builder.html", "classdatabase_1_1testing_1_1mock__database__builder" ],
        [ "scoped_connection", "classdatabase_1_1testing_1_1scoped__connection.html", "classdatabase_1_1testing_1_1scoped__connection" ],
        [ "scoped_test_database", "classdatabase_1_1testing_1_1scoped__test__database.html", "classdatabase_1_1testing_1_1scoped__test__database" ],
        [ "test_timer", "classdatabase_1_1testing_1_1test__timer.html", "classdatabase_1_1testing_1_1test__timer" ]
      ] ],
      [ "tests", "namespacedatabase_1_1tests.html", [
        [ "SQLQueryBuilderTest", "classdatabase_1_1tests_1_1SQLQueryBuilderTest.html", "classdatabase_1_1tests_1_1SQLQueryBuilderTest" ],
        [ "UniversalQueryBuilderTest", "classdatabase_1_1tests_1_1UniversalQueryBuilderTest.html", "classdatabase_1_1tests_1_1UniversalQueryBuilderTest" ]
      ] ],
      [ "utils", "namespacedatabase_1_1utils.html", [
        [ "backend_logger", "classdatabase_1_1utils_1_1backend__logger.html", "classdatabase_1_1utils_1_1backend__logger" ]
      ] ],
      [ "database_context", "classdatabase_1_1database__context.html", "classdatabase_1_1database__context" ],
      [ "database_manager", "classdatabase_1_1database__manager.html", "classdatabase_1_1database__manager" ],
      [ "immutable_query_builder", "classdatabase_1_1immutable__query__builder.html", "classdatabase_1_1immutable__query__builder" ],
      [ "postgres_manager", "classdatabase_1_1postgres__manager.html", "classdatabase_1_1postgres__manager" ],
      [ "query_builder", "classdatabase_1_1query__builder.html", "classdatabase_1_1query__builder" ],
      [ "query_condition", "classdatabase_1_1query__condition.html", "classdatabase_1_1query__condition" ],
      [ "query_dialect", "classdatabase_1_1query__dialect.html", "classdatabase_1_1query__dialect" ]
    ] ],
    [ "AlertSystemTest", "classAlertSystemTest.html", "classAlertSystemTest" ],
    [ "AsyncDatabaseTest", "classAsyncDatabaseTest.html", "classAsyncDatabaseTest" ],
    [ "AsyncExecutorTest", "classAsyncExecutorTest.html", "classAsyncExecutorTest" ],
    [ "AsyncOperationsTest", "classAsyncOperationsTest.html", "classAsyncOperationsTest" ],
    [ "AsyncResultTest", "classAsyncResultTest.html", "classAsyncResultTest" ],
    [ "AsyncStressTest", "classAsyncStressTest.html", "classAsyncStressTest" ],
    [ "BackendBaseTest", "classBackendBaseTest.html", "classBackendBaseTest" ],
    [ "BackendContractTest", "classBackendContractTest.html", "classBackendContractTest" ],
    [ "BackendRegistryTest", "classBackendRegistryTest.html", "classBackendRegistryTest" ],
    [ "BenchmarkUser", "classBenchmarkUser.html", "classBenchmarkUser" ],
    [ "ConcurrentOperationsIntegrationTest", "classConcurrentOperationsIntegrationTest.html", null ],
    [ "ConnectionMetricsTest", "classConnectionMetricsTest.html", "classConnectionMetricsTest" ],
    [ "ConnectProtocolTest", "classConnectProtocolTest.html", null ],
    [ "CredentialSecurityTest", "classCredentialSecurityTest.html", "classCredentialSecurityTest" ],
    [ "DatabaseTest", "classDatabaseTest.html", "classDatabaseTest" ],
    [ "DataMaskingTest", "classDataMaskingTest.html", "classDataMaskingTest" ],
    [ "EntityMetadataTest", "classEntityMetadataTest.html", "classEntityMetadataTest" ],
    [ "ErrorHandlingIntegrationTest", "classErrorHandlingIntegrationTest.html", null ],
    [ "ErrorProtocolTest", "classErrorProtocolTest.html", null ],
    [ "FieldMetadataTest", "classFieldMetadataTest.html", null ],
    [ "FilteredSummaryTest", "classFilteredSummaryTest.html", "classFilteredSummaryTest" ],
    [ "FullSystemIntegrationTest", "classFullSystemIntegrationTest.html", null ],
    [ "ImmutableQueryBuilderTest", "classImmutableQueryBuilderTest.html", "classImmutableQueryBuilderTest" ],
    [ "IntegrationTestBase", "classIntegrationTestBase.html", "classIntegrationTestBase" ],
    [ "IntegrationTestUser", "classIntegrationTestUser.html", "classIntegrationTestUser" ],
    [ "MemoryStressTest", "classMemoryStressTest.html", "classMemoryStressTest" ],
    [ "MessageHeaderTest", "classMessageHeaderTest.html", null ],
    [ "MetricLifecycleTest", "classMetricLifecycleTest.html", "classMetricLifecycleTest" ],
    [ "MetricsOutputTest", "classMetricsOutputTest.html", "classMetricsOutputTest" ],
    [ "MongoDBBackendTest", "classMongoDBBackendTest.html", "classMongoDBBackendTest" ],
    [ "MonitoringEnabledTest", "classMonitoringEnabledTest.html", "classMonitoringEnabledTest" ],
    [ "ORMSecurityIntegrationTest", "classORMSecurityIntegrationTest.html", "classORMSecurityIntegrationTest" ],
    [ "ORMTest", "classORMTest.html", "classORMTest" ],
    [ "PerformanceAlertTest", "classPerformanceAlertTest.html", null ],
    [ "PerformanceAsyncIntegrationTest", "classPerformanceAsyncIntegrationTest.html", null ],
    [ "PerformanceMonitorQueryTest", "classPerformanceMonitorQueryTest.html", "classPerformanceMonitorQueryTest" ],
    [ "PerformanceMonitorTest", "classPerformanceMonitorTest.html", "classPerformanceMonitorTest" ],
    [ "PoolMetricsTest", "classPoolMetricsTest.html", "classPoolMetricsTest" ],
    [ "post_entity", "classpost__entity.html", "classpost__entity" ],
    [ "PostgreSQLBackendTest", "classPostgreSQLBackendTest.html", "classPostgreSQLBackendTest" ],
    [ "Product", "classProduct.html", "classProduct" ],
    [ "PrometheusExporterTest", "classPrometheusExporterTest.html", null ],
    [ "QueryBuilderTest", "classQueryBuilderTest.html", "classQueryBuilderTest" ],
    [ "QueryHistoryTest", "classQueryHistoryTest.html", "classQueryHistoryTest" ],
    [ "QueryProtocolTest", "classQueryProtocolTest.html", null ],
    [ "QueryTimerTest", "classQueryTimerTest.html", "classQueryTimerTest" ],
    [ "RedisBackendTest", "classRedisBackendTest.html", "classRedisBackendTest" ],
    [ "SagaBuilderTest", "classSagaBuilderTest.html", "classSagaBuilderTest" ],
    [ "sample_info", "structsample__info.html", "structsample__info" ],
    [ "sample_runner", "classsample__runner.html", "classsample__runner" ],
    [ "SecurityMonitoringIntegrationTest", "classSecurityMonitoringIntegrationTest.html", null ],
    [ "SecurityTest", "classSecurityTest.html", "classSecurityTest" ],
    [ "SerializerEdgeCaseTest", "classSerializerEdgeCaseTest.html", null ],
    [ "SQLInjectionTest", "classSQLInjectionTest.html", "classSQLInjectionTest" ],
    [ "SQLiteBackendTest", "classSQLiteBackendTest.html", "classSQLiteBackendTest" ],
    [ "StreamProcessorTest", "classStreamProcessorTest.html", "classStreamProcessorTest" ],
    [ "TestUser", "classTestUser.html", "classTestUser" ],
    [ "transaction_guard", "classtransaction__guard.html", "classtransaction__guard" ],
    [ "TransactionCoordinatorTest", "classTransactionCoordinatorTest.html", "classTransactionCoordinatorTest" ],
    [ "TransactionProtocolTest", "classTransactionProtocolTest.html", null ],
    [ "User", "classUser.html", "classUser" ],
    [ "user_entity", "classuser__entity.html", "classuser__entity" ],
    [ "ValueFormatterTest", "classValueFormatterTest.html", "classValueFormatterTest" ]
];