var hierarchy =
[
    [ "database::security::access_control", "classdatabase_1_1security_1_1access__control.html", null ],
    [ "database::async::async_database", "classdatabase_1_1async_1_1async__database.html", null ],
    [ "database::async::async_executor", "classdatabase_1_1async_1_1async__executor.html", null ],
    [ "database::async::async_result< T >", "classdatabase_1_1async_1_1async__result.html", null ],
    [ "database::security::audit_log_entry", "structdatabase_1_1security_1_1audit__log__entry.html", null ],
    [ "database::security::audit_logger", "classdatabase_1_1security_1_1audit__logger.html", null ],
    [ "database::testing::backend_expectation", "classdatabase_1_1testing_1_1backend__expectation.html", null ],
    [ "database::testing::backend_expectation_builder", "classdatabase_1_1testing_1_1backend__expectation__builder.html", null ],
    [ "database::utils::backend_logger", "classdatabase_1_1utils_1_1backend__logger.html", null ],
    [ "database::core::backend_registrar< BackendType >", "classdatabase_1_1core_1_1backend__registrar.html", null ],
    [ "database::core::backend_registry", "classdatabase_1_1core_1_1backend__registry.html", null ],
    [ "BenchmarkUser", "classBenchmarkUser.html", null ],
    [ "database::integrated::unified_database_system::builder", "classdatabase_1_1integrated_1_1unified__database__system_1_1builder.html", null ],
    [ "database::query::condition", "structdatabase_1_1query_1_1condition.html", null ],
    [ "database::query::condition_builder", "classdatabase_1_1query_1_1condition__builder.html", null ],
    [ "database::query::condition_builder::condition_node", "structdatabase_1_1query_1_1condition__builder_1_1condition__node.html", null ],
    [ "database::testing::mock_connection_pool::config", "structdatabase_1_1testing_1_1mock__connection__pool_1_1config.html", null ],
    [ "database::protocol::connect_request", "structdatabase_1_1protocol_1_1connect__request.html", null ],
    [ "database::protocol::connect_response", "structdatabase_1_1protocol_1_1connect__response.html", null ],
    [ "database::core::connection_config", "structdatabase_1_1core_1_1connection__config.html", null ],
    [ "database::monitoring::connection_metrics", "structdatabase_1_1monitoring_1_1connection__metrics.html", null ],
    [ "database::security::connection_security", "classdatabase_1_1security_1_1connection__security.html", null ],
    [ "database::integrated::connection_string_builder", "classdatabase_1_1integrated_1_1connection__string__builder.html", null ],
    [ "database::integrated::database_coordinator::coordinator_stats", "structdatabase_1_1integrated_1_1database__coordinator_1_1coordinator__stats.html", null ],
    [ "database::security::credential_manager", "classdatabase_1_1security_1_1credential__manager.html", null ],
    [ "database::monitoring::dashboard_server", "classdatabase_1_1monitoring_1_1dashboard__server.html", null ],
    [ "database::core::database_backend", "classdatabase_1_1core_1_1database__backend.html", [
      [ "database::core::backend_base< mongodb_backend, database_types::mongodb >", "classdatabase_1_1core_1_1backend__base.html", [
        [ "database::backends::mongodb_backend", "classdatabase_1_1backends_1_1mongodb__backend.html", null ]
      ] ],
      [ "database::core::backend_base< postgresql_backend, database_types::postgres >", "classdatabase_1_1core_1_1backend__base.html", [
        [ "database::backends::postgresql_backend", "classdatabase_1_1backends_1_1postgresql__backend.html", null ]
      ] ],
      [ "database::core::backend_base< redis_backend, database_types::redis >", "classdatabase_1_1core_1_1backend__base.html", [
        [ "database::backends::redis_backend", "classdatabase_1_1backends_1_1redis__backend.html", null ]
      ] ],
      [ "database::core::backend_base< sqlite_backend, database_types::sqlite >", "classdatabase_1_1core_1_1backend__base.html", [
        [ "database::backends::sqlite_backend", "classdatabase_1_1backends_1_1sqlite__backend.html", null ]
      ] ],
      [ "database::core::backend_base< Derived, Type >", "classdatabase_1_1core_1_1backend__base.html", null ],
      [ "database::postgres_manager", "classdatabase_1_1postgres__manager.html", null ],
      [ "database::testing::mock_backend", "classdatabase_1_1testing_1_1mock__backend.html", null ],
      [ "database::testing::mock_database", "classdatabase_1_1testing_1_1mock__database.html", null ]
    ] ],
    [ "database::integrated::database_config", "structdatabase_1_1integrated_1_1database__config.html", null ],
    [ "database::database_context", "classdatabase_1_1database__context.html", null ],
    [ "database::integrated::database_coordinator", "classdatabase_1_1integrated_1_1database__coordinator.html", null ],
    [ "database::database_manager", "classdatabase_1_1database__manager.html", null ],
    [ "database::integrated::adapters::database_metrics", "structdatabase_1_1integrated_1_1adapters_1_1database__metrics.html", null ],
    [ "database::integrated::database_metrics", "structdatabase_1_1integrated_1_1database__metrics.html", null ],
    [ "database::integrated::db_logger_config", "structdatabase_1_1integrated_1_1db__logger__config.html", null ],
    [ "database::integrated::db_monitoring_config", "structdatabase_1_1integrated_1_1db__monitoring__config.html", null ],
    [ "database::integrated::db_thread_config", "structdatabase_1_1integrated_1_1db__thread__config.html", null ],
    [ "database::async::transaction_coordinator::distributed_transaction", "structdatabase_1_1async_1_1transaction__coordinator_1_1distributed__transaction.html", null ],
    [ "database::security::encryption_manager", "classdatabase_1_1security_1_1encryption__manager.html", null ],
    [ "database::orm::entity_base", "classdatabase_1_1orm_1_1entity__base.html", [
      [ "IntegrationTestUser", "classIntegrationTestUser.html", null ],
      [ "Product", "classProduct.html", null ],
      [ "TestUser", "classTestUser.html", null ],
      [ "User", "classUser.html", null ],
      [ "post_entity", "classpost__entity.html", null ],
      [ "user_entity", "classuser__entity.html", null ]
    ] ],
    [ "database::orm::entity_manager", "classdatabase_1_1orm_1_1entity__manager.html", null ],
    [ "database::orm::entity_metadata", "classdatabase_1_1orm_1_1entity__metadata.html", null ],
    [ "common::error_info", "structcommon_1_1error__info.html", null ],
    [ "database::protocol::error_response", "structdatabase_1_1protocol_1_1error__response.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "database::testing::backend_exception", "classdatabase_1_1testing_1_1backend__exception.html", null ],
        [ "database::testing::database_exception", "classdatabase_1_1testing_1_1database__exception.html", null ]
      ] ]
    ] ],
    [ "database::testing::expectation", "classdatabase_1_1testing_1_1expectation.html", null ],
    [ "database::testing::expectation_builder", "classdatabase_1_1testing_1_1expectation__builder.html", null ],
    [ "database::async::fallback_context", "classdatabase_1_1async_1_1fallback__context.html", null ],
    [ "std::false_type", null, [
      [ "database::orm::is_entity< T, typename >", "structdatabase_1_1orm_1_1is__entity.html", null ]
    ] ],
    [ "database::orm::field_accessor< T, typename >", "classdatabase_1_1orm_1_1field__accessor.html", null ],
    [ "database::orm::field_metadata", "classdatabase_1_1orm_1_1field__metadata.html", null ],
    [ "database::integrated::health_check", "structdatabase_1_1integrated_1_1health__check.html", null ],
    [ "database::integrated::adapters::backends::health_check_result", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1health__check__result.html", null ],
    [ "database::immutable_query_builder", "classdatabase_1_1immutable__query__builder.html", null ],
    [ "database::integrated::database_coordinator::impl", "classdatabase_1_1integrated_1_1database__coordinator_1_1impl.html", null ],
    [ "database::integrated::unified_database_system::impl", "classdatabase_1_1integrated_1_1unified__database__system_1_1impl.html", null ],
    [ "std::is_convertible", null, [
      [ "database::orm::is_entity< T, std::void_t< typename T::primary_key_type, decltype(std::declval< T >().table_name()), decltype(std::declval< T >().get_metadata()) > >", "structdatabase_1_1orm_1_1is__entity_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1primary__key__9fe9349fbe2e5ada710d0512a44a53a9.html", null ]
    ] ],
    [ "database::query::join_builder", "classdatabase_1_1query_1_1join__builder.html", null ],
    [ "database::query::join_spec", "structdatabase_1_1query_1_1join__spec.html", null ],
    [ "database::integrated::adapters::logger_adapter", "classdatabase_1_1integrated_1_1adapters_1_1logger__adapter.html", null ],
    [ "database::integrated::adapters::backends::logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1logger__backend.html", [
      [ "database::integrated::adapters::backends::common_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1common__logger__backend.html", null ],
      [ "database::integrated::adapters::backends::fallback_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__logger__backend.html", null ],
      [ "database::integrated::adapters::backends::null_logger_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__logger__backend.html", null ]
    ] ],
    [ "database::protocol::message_header", "structdatabase_1_1protocol_1_1message__header.html", null ],
    [ "database::monitoring::metrics_exporter", "classdatabase_1_1monitoring_1_1metrics__exporter.html", [
      [ "database::monitoring::prometheus_exporter", "classdatabase_1_1monitoring_1_1prometheus__exporter.html", null ]
    ] ],
    [ "database::integrated::adapters::backends::metrics_snapshot", "structdatabase_1_1integrated_1_1adapters_1_1backends_1_1metrics__snapshot.html", null ],
    [ "database::testing::mock_backend_builder", "classdatabase_1_1testing_1_1mock__backend__builder.html", null ],
    [ "database::testing::mock_connection_pool", "classdatabase_1_1testing_1_1mock__connection__pool.html", null ],
    [ "database::testing::mock_database_builder", "classdatabase_1_1testing_1_1mock__database__builder.html", null ],
    [ "database::integrated::adapters::monitoring_adapter", "classdatabase_1_1integrated_1_1adapters_1_1monitoring__adapter.html", null ],
    [ "database::integrated::adapters::backends::monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1monitoring__backend.html", [
      [ "database::integrated::adapters::backends::fallback_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__monitoring__backend.html", null ],
      [ "database::integrated::adapters::backends::null_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__monitoring__backend.html", null ],
      [ "database::integrated::adapters::backends::system_monitoring_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1system__monitoring__backend.html", null ]
    ] ],
    [ "database::monitoring::performance_alert", "classdatabase_1_1monitoring_1_1performance__alert.html", null ],
    [ "database::monitoring::performance_monitor", "classdatabase_1_1monitoring_1_1performance__monitor.html", null ],
    [ "database::monitoring::performance_summary", "structdatabase_1_1monitoring_1_1performance__summary.html", null ],
    [ "database::integrated::pool_config", "structdatabase_1_1integrated_1_1pool__config.html", null ],
    [ "database::monitoring::pool_metrics", "structdatabase_1_1monitoring_1_1pool__metrics.html", null ],
    [ "database::integrated::unified_database_system::pool_stats", "structdatabase_1_1integrated_1_1unified__database__system_1_1pool__stats.html", null ],
    [ "database::protocol::protocol_serializer", "classdatabase_1_1protocol_1_1protocol__serializer.html", null ],
    [ "database::orm::query_builder< EntityType, typename >", "classdatabase_1_1orm_1_1query__builder.html", null ],
    [ "database::query_builder", "classdatabase_1_1query__builder.html", null ],
    [ "database::query_condition", "classdatabase_1_1query__condition.html", null ],
    [ "database::query_dialect", "classdatabase_1_1query__dialect.html", [
      [ "database::detail::sql_dialect", "classdatabase_1_1detail_1_1sql__dialect.html", null ]
    ] ],
    [ "database::monitoring::query_metrics", "structdatabase_1_1monitoring_1_1query__metrics.html", null ],
    [ "database::integrated::query_param", "structdatabase_1_1integrated_1_1query__param.html", null ],
    [ "database::protocol::query_request", "structdatabase_1_1protocol_1_1query__request.html", null ],
    [ "database::protocol::query_response", "structdatabase_1_1protocol_1_1query__response.html", null ],
    [ "database::integrated::query_result", "structdatabase_1_1integrated_1_1query__result.html", null ],
    [ "database::security::query_security", "classdatabase_1_1security_1_1query__security.html", null ],
    [ "database::monitoring::query_timer", "classdatabase_1_1monitoring_1_1query__timer.html", null ],
    [ "common::Result< T >", "classcommon_1_1Result.html", null ],
    [ "database::async::result_type< T >", "classdatabase_1_1async_1_1result__type.html", null ],
    [ "database::async::result_void_type", "classdatabase_1_1async_1_1result__void__type.html", null ],
    [ "database::security::access_control::role", "structdatabase_1_1security_1_1access__control_1_1role.html", null ],
    [ "database::async::saga_builder", "classdatabase_1_1async_1_1saga__builder.html", null ],
    [ "database::async::saga_builder::saga_step", "structdatabase_1_1async_1_1saga__builder_1_1saga__step.html", null ],
    [ "sample_info", "structsample__info.html", null ],
    [ "sample_runner", "classsample__runner.html", null ],
    [ "database::testing::scoped_connection", "classdatabase_1_1testing_1_1scoped__connection.html", null ],
    [ "database::testing::scoped_test_database", "classdatabase_1_1testing_1_1scoped__test__database.html", null ],
    [ "database::security::security_monitor::security_alert", "structdatabase_1_1security_1_1security__monitor_1_1security__alert.html", null ],
    [ "database::security::security_credentials", "structdatabase_1_1security_1_1security__credentials.html", null ],
    [ "database::security::security_monitor", "classdatabase_1_1security_1_1security__monitor.html", null ],
    [ "database::query::sql_dialect", "classdatabase_1_1query_1_1sql__dialect.html", [
      [ "database::query::postgresql_dialect", "classdatabase_1_1query_1_1postgresql__dialect.html", null ],
      [ "database::query::sqlite_dialect", "classdatabase_1_1query_1_1sqlite__dialect.html", null ]
    ] ],
    [ "database::testing::mock_connection_pool::stats", "structdatabase_1_1testing_1_1mock__connection__pool_1_1stats.html", null ],
    [ "database::async::stream_processor::stream_event", "structdatabase_1_1async_1_1stream__processor_1_1stream__event.html", null ],
    [ "database::async::stream_processor", "classdatabase_1_1async_1_1stream__processor.html", null ],
    [ "testing::Test", null, [
      [ "AlertSystemTest", "classAlertSystemTest.html", null ],
      [ "AsyncDatabaseTest", "classAsyncDatabaseTest.html", null ],
      [ "AsyncExecutorTest", "classAsyncExecutorTest.html", null ],
      [ "AsyncOperationsTest", "classAsyncOperationsTest.html", null ],
      [ "AsyncResultTest", "classAsyncResultTest.html", null ],
      [ "AsyncStressTest", "classAsyncStressTest.html", null ],
      [ "BackendBaseTest", "classBackendBaseTest.html", null ],
      [ "BackendContractTest", "classBackendContractTest.html", null ],
      [ "BackendRegistryTest", "classBackendRegistryTest.html", null ],
      [ "ConnectProtocolTest", "classConnectProtocolTest.html", null ],
      [ "ConnectionMetricsTest", "classConnectionMetricsTest.html", null ],
      [ "CredentialSecurityTest", "classCredentialSecurityTest.html", null ],
      [ "DataMaskingTest", "classDataMaskingTest.html", null ],
      [ "DatabaseTest", "classDatabaseTest.html", null ],
      [ "EntityMetadataTest", "classEntityMetadataTest.html", null ],
      [ "ErrorProtocolTest", "classErrorProtocolTest.html", null ],
      [ "FieldMetadataTest", "classFieldMetadataTest.html", null ],
      [ "FilteredSummaryTest", "classFilteredSummaryTest.html", null ],
      [ "ImmutableQueryBuilderTest", "classImmutableQueryBuilderTest.html", null ],
      [ "IntegrationTestBase", "classIntegrationTestBase.html", [
        [ "ConcurrentOperationsIntegrationTest", "classConcurrentOperationsIntegrationTest.html", null ],
        [ "ErrorHandlingIntegrationTest", "classErrorHandlingIntegrationTest.html", null ],
        [ "FullSystemIntegrationTest", "classFullSystemIntegrationTest.html", null ],
        [ "ORMSecurityIntegrationTest", "classORMSecurityIntegrationTest.html", null ],
        [ "PerformanceAsyncIntegrationTest", "classPerformanceAsyncIntegrationTest.html", null ],
        [ "SecurityMonitoringIntegrationTest", "classSecurityMonitoringIntegrationTest.html", null ]
      ] ],
      [ "MemoryStressTest", "classMemoryStressTest.html", null ],
      [ "MessageHeaderTest", "classMessageHeaderTest.html", null ],
      [ "MetricLifecycleTest", "classMetricLifecycleTest.html", null ],
      [ "MetricsOutputTest", "classMetricsOutputTest.html", null ],
      [ "MongoDBBackendTest", "classMongoDBBackendTest.html", null ],
      [ "MonitoringEnabledTest", "classMonitoringEnabledTest.html", null ],
      [ "ORMTest", "classORMTest.html", null ],
      [ "PerformanceAlertTest", "classPerformanceAlertTest.html", null ],
      [ "PerformanceMonitorQueryTest", "classPerformanceMonitorQueryTest.html", null ],
      [ "PerformanceMonitorTest", "classPerformanceMonitorTest.html", null ],
      [ "PoolMetricsTest", "classPoolMetricsTest.html", null ],
      [ "PostgreSQLBackendTest", "classPostgreSQLBackendTest.html", null ],
      [ "PrometheusExporterTest", "classPrometheusExporterTest.html", null ],
      [ "QueryBuilderTest", "classQueryBuilderTest.html", null ],
      [ "QueryHistoryTest", "classQueryHistoryTest.html", null ],
      [ "QueryProtocolTest", "classQueryProtocolTest.html", null ],
      [ "QueryTimerTest", "classQueryTimerTest.html", null ],
      [ "RedisBackendTest", "classRedisBackendTest.html", null ],
      [ "SQLInjectionTest", "classSQLInjectionTest.html", null ],
      [ "SQLiteBackendTest", "classSQLiteBackendTest.html", null ],
      [ "SagaBuilderTest", "classSagaBuilderTest.html", null ],
      [ "SecurityTest", "classSecurityTest.html", null ],
      [ "SerializerEdgeCaseTest", "classSerializerEdgeCaseTest.html", null ],
      [ "StreamProcessorTest", "classStreamProcessorTest.html", null ],
      [ "TransactionCoordinatorTest", "classTransactionCoordinatorTest.html", null ],
      [ "TransactionProtocolTest", "classTransactionProtocolTest.html", null ],
      [ "ValueFormatterTest", "classValueFormatterTest.html", null ],
      [ "database::query::tests::CrossDialectTest", "classdatabase_1_1query_1_1tests_1_1CrossDialectTest.html", null ],
      [ "database::query::tests::PostgreSQLDialectTest", "classdatabase_1_1query_1_1tests_1_1PostgreSQLDialectTest.html", null ],
      [ "database::query::tests::SQLiteDialectTest", "classdatabase_1_1query_1_1tests_1_1SQLiteDialectTest.html", null ],
      [ "database::tests::SQLQueryBuilderTest", "classdatabase_1_1tests_1_1SQLQueryBuilderTest.html", null ],
      [ "database::tests::UniversalQueryBuilderTest", "classdatabase_1_1tests_1_1UniversalQueryBuilderTest.html", null ]
    ] ],
    [ "database::testing::test_timer", "classdatabase_1_1testing_1_1test__timer.html", null ],
    [ "database::integrated::adapters::thread_adapter", "classdatabase_1_1integrated_1_1adapters_1_1thread__adapter.html", null ],
    [ "database::integrated::adapters::backends::thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1thread__backend.html", [
      [ "database::integrated::adapters::backends::fallback_thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1fallback__thread__backend.html", null ],
      [ "database::integrated::adapters::backends::null_thread_backend", "classdatabase_1_1integrated_1_1adapters_1_1backends_1_1null__thread__backend.html", null ]
    ] ],
    [ "database::integrated::transaction", "classdatabase_1_1integrated_1_1transaction.html", [
      [ "database::integrated::transaction_impl", "classdatabase_1_1integrated_1_1transaction__impl.html", null ]
    ] ],
    [ "database::async::transaction_coordinator", "classdatabase_1_1async_1_1transaction__coordinator.html", null ],
    [ "transaction_guard", "classtransaction__guard.html", null ],
    [ "database::protocol::transaction_request", "structdatabase_1_1protocol_1_1transaction__request.html", null ],
    [ "database::protocol::transaction_response", "structdatabase_1_1protocol_1_1transaction__response.html", null ],
    [ "database::integrated::unified_database_system", "classdatabase_1_1integrated_1_1unified__database__system.html", null ],
    [ "database::integrated::unified_db_config", "structdatabase_1_1integrated_1_1unified__db__config.html", null ],
    [ "database::security::access_control::user_session", "structdatabase_1_1security_1_1access__control_1_1user__session.html", null ],
    [ "database::query::value_formatter", "classdatabase_1_1query_1_1value__formatter.html", null ]
];